export function getTeamDisplayName(code: string): string {
  const map: Record<string, string> = {
    ARG: "Argentina",
    AUS: "Australia",
    AUT: "Austria",
    ALG: "Algeria",
    BEL: "Belgium",
    BRA: "Brazil",
    CAN: "Canada",
    COL: "Colombia",
    CRO: "Croatia",
    CZE: "Czech Republic",
    ECU: "Ecuador",
    EGY: "Egypt",
    ENG: "England",
    FRA: "France",
    GER: "Germany",
    GHA: "Ghana",
    HAI: "Haiti",
    IRN: "Iran",
    IRQ: "Iraq",
    JPN: "Japan",
    JOR: "Jordan",
    KOR: "South Korea",
    KSA: "Saudi Arabia",
    MAR: "Morocco",
    MEX: "Mexico",
    NED: "Netherlands",
    NOR: "Norway",
    NZL: "New Zealand",
    PAN: "Panama",
    PAR: "Paraguay",
    POR: "Portugal",
    QAT: "Qatar",
    RSA: "South Africa",
    SCO: "Scotland",
    SEN: "Senegal",
    ESP: "Spain",
    SUI: "Switzerland",
    SWE: "Sweden",
    TUN: "Tunisia",
    TUR: "Türkiye",
    URU: "Uruguay",
    USA: "United States",
    CIV: "Ivory Coast",
    CPV: "Cape Verde",
    COD: "DR Congo",
    CUW: "Curaçao",
    BIH: "Bosnia and Herzegovina",
  };

  return map[code.toUpperCase()] ?? "Unknown country";
}
